/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogImport } from './routes/blog'
import { Route as AdminLoginImport } from './routes/admin-login'
import { Route as AdminDashboardImport } from './routes/admin-dashboard'
import { Route as BlogPostPageImport } from './routes/Blog-post-page'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BlogPostPageRoute = BlogPostPageImport.update({
  id: '/Blog-post-page',
  path: '/Blog-post-page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Blog-post-page': {
      id: '/Blog-post-page'
      path: '/Blog-post-page'
      fullPath: '/Blog-post-page'
      preLoaderRoute: typeof BlogPostPageImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Blog-post-page': typeof BlogPostPageRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Blog-post-page': typeof BlogPostPageRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Blog-post-page': typeof BlogPostPageRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Blog-post-page'
    | '/admin-dashboard'
    | '/admin-login'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Blog-post-page' | '/admin-dashboard' | '/admin-login' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/Blog-post-page'
    | '/admin-dashboard'
    | '/admin-login'
    | '/blog'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogPostPageRoute: typeof BlogPostPageRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogRoute: typeof BlogRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogPostPageRoute: BlogPostPageRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogRoute: BlogRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Blog-post-page",
        "/admin-dashboard",
        "/admin-login",
        "/blog"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Blog-post-page": {
      "filePath": "Blog-post-page.tsx"
    },
    "/admin-dashboard": {
      "filePath": "admin-dashboard.tsx"
    },
    "/admin-login": {
      "filePath": "admin-login.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
